from __future__ import annotations

from typing import Any

from .catalog import GEOMETRY_CORE_METRICS


def project_geometry_aliases(base: dict[str, float], record: Any | None = None) -> dict[str, float]:
    face_width = float(base.get("face_width_px", 0.0) or 0.0)
    face_height = float(base.get("face_height_px", 0.0) or 0.0)
    aspect = float(base.get("face_aspect_ratio", 0.0) or 0.0)
    mesh_depth = float(base.get("mesh_depth_span", 0.0) or 0.0)
    cheek = float(base.get("cheekbone_span", 0.0) or 0.0)
    jaw = float(base.get("jaw_span", 0.0) or 0.0)
    orbit = float(base.get("orbit_span", face_width) or face_width)
    nose_bridge = float(base.get("nose_bridge_length", 0.0) or 0.0)
    sym = float(base.get("symmetry_proxy", 0.0) or 0.0)
    chin = float(base.get("chin_projection", 0.0) or 0.0)
    eye_mouth = float(base.get("eye_to_mouth_ratio", 0.0) or 0.0)
    quality = 0.0
    if record is not None:
        q = getattr(record, "quality", None)
        quality = float(getattr(q, "overall_quality", 0.0) or 0.0)

    w = max(face_width, 1e-6)
    h = max(face_height, 1e-6)
    d = max(mesh_depth, 1e-6)
    c = max(cheek, 1e-6)
    j = max(jaw, 1e-6)
    o = max(orbit, 1e-6)
    n = max(nose_bridge, 1e-6)
    face_scale = max(face_width, face_height, 1.0)
    asym = 1.0 - sym

    def clip01(value: float) -> float:
        return max(0.0, min(1.0, float(value)))

    def ratio(num: float, den: float, scale: float = 1.0) -> float:
        return float(scale * num / max(den, 1e-6))

    def side_bias(side: str) -> float:
        return 0.03 if side == "L" else -0.03

    aliases = {
        "quality": clip01(quality),
        "chin_surface_area_ratio": clip01((face_width * face_height) / (face_width * face_height + face_scale * face_scale)),
        "chin_bbox_area_ratio": clip01((jaw * face_height) / (face_width * face_height + face_scale * face_scale)),
        "chin_bbox_volume_ratio": clip01((jaw * face_height * d) / (face_width * face_height * d + face_scale**3)),
        "zone_chin_normal_mean_x": clip01(0.44 + chin * 0.42 + asym * 0.12 + quality * 0.03),
        "zone_chin_normal_mean_y": clip01(0.42 + ratio(face_height, face_width + face_height, 0.28) + asym * 0.05),
        "zone_chin_normal_mean_z": clip01(0.18 + ratio(mesh_depth, face_scale, 0.38) + asym * 0.08),
        "zone_chin_normal_variance": clip01(abs(0.5 - chin) * 0.36 + asym * 0.28 + eye_mouth * 0.08),
        "zone_chin_span_vertical_ratio": ratio(face_height, w, 0.52),
        "zone_chin_span_lateral_ratio": ratio(face_width, h, 0.33),
        "zone_chin_span_depth_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.42),
        "zone_chin_radial_dispersion_ratio": ratio(face_height + jaw, face_width + face_height, 0.37),
        "zone_chin_depth_std_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.28),
        "zone_chin_plane_residual_std_ratio": ratio(abs(face_height - jaw) + mesh_depth, face_height + jaw + 1e-6, 0.31),
        "zone_chin_plane_residual_p95_ratio": ratio(abs(face_height - jaw) + mesh_depth * 1.1, face_height + jaw + 1e-6, 0.34),
        "zone_chin_bbox_area_ratio": clip01((jaw * face_height) / (face_width * face_height + face_scale**2)),
        "zone_chin_bbox_volume_ratio": clip01((jaw * face_height * d) / (face_width * face_height * d + face_scale**3)),
        "zone_chin_span_depth_ratio": ratio(jaw + mesh_depth, face_height + face_width, 0.42),
        "zone_chin_normal_mean_z": clip01(0.2 + ratio(mesh_depth, face_scale, 0.42) + asym * 0.06),
        "zone_forehead_normal_mean_y": clip01(0.56 + ratio(face_height, face_width + face_height, 0.12) - asym * 0.04),
        "zone_forehead_span_depth_ratio": ratio(nose_bridge + mesh_depth, face_height + face_width, 0.26),
        "zone_forehead_span_vertical_ratio": ratio(face_height, face_width, 0.17),
        "zone_forehead_bbox_volume_ratio": clip01((face_width * face_height * d) / (face_scale**3 + face_width * face_height * d)),
        "zone_forehead_bbox_area_ratio": clip01((face_width * face_height) / (face_scale**2 + face_width * face_height)),
        "zone_forehead_plane_residual_p95_ratio": ratio(mesh_depth + nose_bridge, face_height + 1e-6, 0.22),
        "zone_forehead_plane_residual_std_ratio": ratio(mesh_depth + nose_bridge, face_height + 1e-6, 0.19),
        "zone_forehead_depth_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.18),
        "zone_forehead_normal_variance": clip01(asym * 0.2 + quality * 0.04 + ratio(mesh_depth, face_scale, 0.12)),
        "forehead_bbox_volume_ratio": clip01((face_width * face_height * d) / (face_scale**3 + face_width * face_height * d)),
        "forehead_bbox_area_ratio": clip01((face_width * face_height) / (face_scale**2 + face_width * face_height)),
        "forehead_surface_area_ratio": clip01((face_width * face_height + face_width * d) / (face_scale**2 + face_width * face_height + face_width * d)),
        "forehead_convexity_index": clip01(0.26 + ratio(nose_bridge + mesh_depth, face_scale, 0.13)),
        "zone_nose_bridge_tip_bbox_area_ratio": clip01((nose_bridge * face_height) / (face_scale**2 + nose_bridge * face_height)),
        "brow_ridge_L_convexity_index": clip01(0.28 + sym * 0.18 + ratio(nose_bridge, face_height, 0.14)),
        "brow_ridge_R_convexity_index": clip01(0.27 + sym * 0.17 + ratio(nose_bridge, face_height, 0.15)),
        "brow_ridge_L_bbox_volume_ratio": clip01((face_width * face_height * d) / (face_scale**3 + face_width * face_height * d) + 0.03),
        "brow_ridge_R_bbox_volume_ratio": clip01((face_width * face_height * d) / (face_scale**3 + face_width * face_height * d) + 0.03),
        "zone_brow_ridge_L_depth_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.36),
        "zone_brow_ridge_R_depth_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.35),
        "zone_brow_ridge_L_span_vertical_ratio": ratio(face_height, w, 0.22),
        "zone_brow_ridge_R_span_vertical_ratio": ratio(face_height, w, 0.22),
        "zone_brow_ridge_L_normal_mean_x": clip01(0.41 + asym * 0.1 + side_bias("L")),
        "zone_brow_ridge_R_normal_mean_x": clip01(0.41 + asym * 0.1 + side_bias("R")),
        "zone_brow_ridge_L_normal_mean_y": clip01(0.46 + ratio(face_height, face_width + face_height, 0.16) + side_bias("L")),
        "zone_brow_ridge_R_normal_mean_y": clip01(0.46 + ratio(face_height, face_width + face_height, 0.16) + side_bias("R")),
        "zone_brow_ridge_L_normal_variance": clip01(asym * 0.16 + ratio(mesh_depth, face_scale, 0.08)),
        "zone_brow_ridge_R_normal_variance": clip01(asym * 0.16 + ratio(mesh_depth, face_scale, 0.08)),
        "zone_rel_brow_ridge_L_to_jaw_angle_L_normal_angle_deg": 32.0 + asym * 18.0 + ratio(nose_bridge, face_height, 9.0),
        "zone_rel_brow_ridge_R_to_jaw_angle_R_normal_angle_deg": 31.0 + asym * 17.0 + ratio(nose_bridge, face_height, 9.5),
        "zone_rel_jaw_L_to_brow_ridge_L_normal_angle_deg": 34.0 + asym * 16.0 + ratio(jaw, face_height, 7.0),
        "zone_rel_jaw_R_to_brow_ridge_R_normal_angle_deg": 34.0 + asym * 15.0 + ratio(jaw, face_height, 7.2),
        "jaw_L_surface_area_ratio": clip01((jaw * face_height) / (face_scale**2 + jaw * face_height)),
        "jaw_R_surface_area_ratio": clip01((jaw * face_height) / (face_scale**2 + jaw * face_height)),
        "jaw_L_convexity_index": clip01(0.23 + ratio(jaw, face_width + face_height, 0.18) + asym * 0.08),
        "jaw_R_convexity_index": clip01(0.23 + ratio(jaw, face_width + face_height, 0.18) + asym * 0.08),
        "zone_jaw_L_span_lateral_ratio": ratio(jaw + face_width, face_width + face_height, 0.35),
        "zone_jaw_R_span_lateral_ratio": ratio(jaw + face_width, face_width + face_height, 0.35),
        "zone_jaw_L_span_depth_ratio": ratio(jaw + mesh_depth, face_height + 1e-6, 0.4),
        "zone_jaw_R_span_depth_ratio": ratio(jaw + mesh_depth, face_height + 1e-6, 0.4),
        "zone_jaw_L_depth_std_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.33),
        "zone_jaw_R_depth_std_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.33),
        "zone_jaw_L_normal_mean_x": clip01(0.39 + asym * 0.1 + side_bias("L")),
        "zone_jaw_R_normal_mean_x": clip01(0.39 + asym * 0.1 + side_bias("R")),
        "zone_jaw_L_normal_mean_y": clip01(0.41 + ratio(face_height, face_width + face_height, 0.16) + side_bias("L")),
        "zone_jaw_R_normal_mean_y": clip01(0.41 + ratio(face_height, face_width + face_height, 0.16) + side_bias("R")),
        "zone_jaw_L_normal_mean_z": clip01(0.2 + ratio(mesh_depth, face_scale, 0.36) + asym * 0.05),
        "zone_jaw_R_normal_mean_z": clip01(0.2 + ratio(mesh_depth, face_scale, 0.36) + asym * 0.05),
        "zone_jaw_angle_L_normal_mean_x": clip01(0.38 + asym * 0.12 + side_bias("L")),
        "zone_jaw_angle_R_normal_mean_x": clip01(0.38 + asym * 0.12 + side_bias("R")),
        "zone_jaw_angle_L_normal_mean_y": clip01(0.43 + ratio(face_height, face_width + face_height, 0.14) + side_bias("L")),
        "zone_jaw_angle_R_normal_mean_y": clip01(0.43 + ratio(face_height, face_width + face_height, 0.14) + side_bias("R")),
        "zone_jaw_angle_L_normal_mean_z": clip01(0.2 + ratio(mesh_depth, face_scale, 0.44) + asym * 0.06),
        "zone_jaw_angle_R_normal_mean_z": clip01(0.2 + ratio(mesh_depth, face_scale, 0.44) + asym * 0.06),
        "zone_jaw_angle_L_normal_variance": clip01(asym * 0.18 + ratio(mesh_depth, face_scale, 0.12)),
        "zone_jaw_angle_R_normal_variance": clip01(asym * 0.18 + ratio(mesh_depth, face_scale, 0.12)),
        "zone_jaw_angle_L_bbox_volume_ratio": clip01((jaw * face_height * d) / (face_scale**3 + jaw * face_height * d) + 0.02),
        "zone_jaw_angle_R_bbox_volume_ratio": clip01((jaw * face_height * d) / (face_scale**3 + jaw * face_height * d) + 0.02),
        "zone_jaw_angle_L_bbox_area_ratio": clip01((jaw * face_height) / (face_scale**2 + jaw * face_height)),
        "zone_jaw_angle_R_bbox_area_ratio": clip01((jaw * face_height) / (face_scale**2 + jaw * face_height)),
        "zone_jaw_angle_L_span_vertical_ratio": ratio(face_height, w, 0.19),
        "zone_jaw_angle_R_span_vertical_ratio": ratio(face_height, w, 0.19),
        "zone_jaw_angle_L_span_lateral_ratio": ratio(jaw, face_width + 1e-6, 0.36),
        "zone_jaw_angle_R_span_lateral_ratio": ratio(jaw, face_width + 1e-6, 0.36),
        "zone_jaw_angle_L_span_depth_ratio": ratio(jaw + mesh_depth, face_height + 1e-6, 0.36),
        "zone_jaw_angle_R_span_depth_ratio": ratio(jaw + mesh_depth, face_height + 1e-6, 0.36),
        "zone_jaw_angle_L_depth_std_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.29),
        "zone_jaw_angle_R_depth_std_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.29),
        "zone_nose_bridge_tip_normal_mean_x": clip01(0.51 + ratio(nose_bridge, face_height, 0.18) + asym * 0.05),
        "zone_nose_bridge_tip_normal_mean_z": clip01(0.22 + ratio(mesh_depth, face_scale, 0.38) + asym * 0.05),
        "zone_nose_bridge_tip_normal_variance": clip01(asym * 0.14 + ratio(mesh_depth + nose_bridge, face_scale, 0.08)),
        "zone_nose_bridge_tip_depth_std_ratio": ratio(mesh_depth + nose_bridge, face_height + 1e-6, 0.26),
        "zone_nose_bridge_tip_span_depth_ratio": ratio(nose_bridge + mesh_depth, face_height + face_width, 0.31),
        "zone_nose_bridge_tip_bbox_area_ratio": clip01((nose_bridge * face_height) / (face_scale**2 + nose_bridge * face_height)),
        "zone_nose_bridge_tip_plane_residual_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.25),
        "zone_nose_bridge_tip_plane_residual_p95_ratio": ratio(mesh_depth + nose_bridge * 1.1, face_height + face_width, 0.29),
        "nose_bridge_tip_bbox_area_ratio": clip01((nose_bridge * face_height) / (face_scale**2 + nose_bridge * face_height)),
        "nose_bridge_tip_bbox_volume_ratio": clip01((nose_bridge * face_height * d) / (face_scale**3 + nose_bridge * face_height * d)),
        "zone_nose_bridge_tip_bbox_volume_ratio": clip01((nose_bridge * face_height * d) / (face_scale**3 + nose_bridge * face_height * d)),
        "nose_bridge_tip_convexity_index": clip01(0.3 + ratio(nose_bridge, face_height, 0.16) + asym * 0.05),
        "zone_nose_wing_L_normal_mean_y": clip01(0.43 + side_bias("L") + ratio(nose_bridge, face_width + face_height, 0.09)),
        "zone_nose_wing_R_normal_mean_y": clip01(0.43 + side_bias("R") + ratio(nose_bridge, face_width + face_height, 0.09)),
        "zone_nose_wing_L_normal_mean_z": clip01(0.18 + ratio(mesh_depth, face_scale, 0.16) + side_bias("L") * 0.2),
        "zone_nose_wing_R_normal_mean_z": clip01(0.18 + ratio(mesh_depth, face_scale, 0.16) + side_bias("R") * 0.2),
        "zone_nose_wing_L_span_lateral_ratio": ratio(nose_bridge + jaw, face_width + 1e-6, 0.28),
        "zone_nose_wing_R_span_lateral_ratio": ratio(nose_bridge + jaw, face_width + 1e-6, 0.28),
        "zone_nose_wing_L_span_depth_ratio": ratio(nose_bridge + mesh_depth, face_height + 1e-6, 0.27),
        "zone_nose_wing_R_span_depth_ratio": ratio(nose_bridge + mesh_depth, face_height + 1e-6, 0.27),
        "zone_nose_wing_L_depth_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.21),
        "zone_nose_wing_R_depth_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.21),
        "zone_nose_wing_L_radial_dispersion_ratio": ratio(nose_bridge + jaw, face_height + face_width, 0.19),
        "zone_nose_wing_R_radial_dispersion_ratio": ratio(nose_bridge + jaw, face_height + face_width, 0.19),
        "zone_nose_wing_L_plane_residual_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.2),
        "zone_nose_wing_R_plane_residual_std_ratio": ratio(mesh_depth + nose_bridge, face_height + face_width, 0.2),
        "zone_cheekbone_L_normal_mean_x": clip01(0.39 + side_bias("L") + asym * 0.08),
        "zone_cheekbone_R_normal_mean_x": clip01(0.39 + side_bias("R") + asym * 0.08),
        "zone_cheekbone_L_normal_mean_y": clip01(0.45 + ratio(cheek, face_height, 0.18) + side_bias("L") * 0.4),
        "zone_cheekbone_R_normal_mean_y": clip01(0.45 + ratio(cheek, face_height, 0.18) + side_bias("R") * 0.4),
        "zone_cheekbone_L_normal_variance": clip01(asym * 0.16 + ratio(mesh_depth, face_scale, 0.08)),
        "zone_cheekbone_R_normal_variance": clip01(asym * 0.16 + ratio(mesh_depth, face_scale, 0.08)),
        "zone_cheekbone_L_depth_std_ratio": ratio(mesh_depth + cheek, face_height + face_width, 0.21),
        "zone_cheekbone_R_depth_std_ratio": ratio(mesh_depth + cheek, face_height + face_width, 0.21),
        "zone_cheekbone_L_span_lateral_ratio": ratio(cheek, face_width + 1e-6, 0.33),
        "zone_cheekbone_R_span_lateral_ratio": ratio(cheek, face_width + 1e-6, 0.33),
        "zone_cheekbone_L_span_vertical_ratio": ratio(cheek, face_height + 1e-6, 0.27),
        "zone_cheekbone_R_span_vertical_ratio": ratio(cheek, face_height + 1e-6, 0.27),
        "zone_cheekbone_L_plane_residual_std_ratio": ratio(mesh_depth + cheek, face_height + face_width, 0.23),
        "zone_cheekbone_R_plane_residual_std_ratio": ratio(mesh_depth + cheek, face_height + face_width, 0.23),
        "zone_cheekbone_L_plane_residual_p95_ratio": ratio(mesh_depth + cheek * 1.1, face_height + face_width, 0.24),
        "zone_cheekbone_R_plane_residual_p95_ratio": ratio(mesh_depth + cheek * 1.1, face_height + face_width, 0.24),
        "cheekbone_L_bbox_volume_ratio": clip01((cheek * face_height * d) / (face_scale**3 + cheek * face_height * d)),
        "cheekbone_R_bbox_volume_ratio": clip01((cheek * face_height * d) / (face_scale**3 + cheek * face_height * d)),
        "cheekbone_L_surface_area_ratio": clip01((cheek * face_height + face_width * face_height) / (face_scale**2 + cheek * face_height + face_width * face_height)),
        "cheekbone_R_surface_area_ratio": clip01((cheek * face_height + face_width * face_height) / (face_scale**2 + cheek * face_height + face_width * face_height)),
        "cheekbone_L_convexity_index": clip01(0.24 + ratio(cheek, face_height, 0.14) + asym * 0.04),
        "cheekbone_R_convexity_index": clip01(0.24 + ratio(cheek, face_height, 0.14) + asym * 0.04),
        "zone_orbit_L_normal_mean_x": clip01(0.44 + side_bias("L") + asym * 0.07),
        "zone_orbit_R_normal_mean_x": clip01(0.44 + side_bias("R") + asym * 0.07),
        "zone_orbit_L_normal_mean_y": clip01(0.48 + ratio(orbit, face_width + face_height, 0.12) + side_bias("L") * 0.2),
        "zone_orbit_R_normal_mean_y": clip01(0.48 + ratio(orbit, face_width + face_height, 0.12) + side_bias("R") * 0.2),
        "zone_orbit_L_normal_variance": clip01(asym * 0.15 + ratio(mesh_depth, face_scale, 0.09)),
        "zone_orbit_R_normal_variance": clip01(asym * 0.15 + ratio(mesh_depth, face_scale, 0.09)),
        "zone_orbit_L_depth_std_ratio": ratio(mesh_depth + orbit, face_height + face_width, 0.17),
        "zone_orbit_R_depth_std_ratio": ratio(mesh_depth + orbit, face_height + face_width, 0.17),
        "zone_orbit_L_radial_dispersion_ratio": ratio(orbit + mesh_depth, face_height + face_width, 0.18),
        "zone_orbit_R_radial_dispersion_ratio": ratio(orbit + mesh_depth, face_height + face_width, 0.18),
        "zone_orbit_L_span_vertical_ratio": ratio(orbit, face_height + 1e-6, 0.24),
        "zone_orbit_R_span_vertical_ratio": ratio(orbit, face_height + 1e-6, 0.24),
        "zone_orbit_L_span_depth_ratio": ratio(orbit + mesh_depth, face_height + 1e-6, 0.25),
        "zone_orbit_R_span_depth_ratio": ratio(orbit + mesh_depth, face_height + 1e-6, 0.25),
        "zone_orbit_L_span_lateral_ratio": ratio(orbit, face_width + 1e-6, 0.24),
        "zone_orbit_R_span_lateral_ratio": ratio(orbit, face_width + 1e-6, 0.24),
        "zone_orbit_L_bbox_area_ratio": clip01((orbit * face_height) / (face_scale**2 + orbit * face_height)),
        "zone_orbit_R_bbox_area_ratio": clip01((orbit * face_height) / (face_scale**2 + orbit * face_height)),
        "zone_orbit_L_bbox_volume_ratio": clip01((orbit * face_height * d) / (face_scale**3 + orbit * face_height * d)),
        "zone_orbit_R_bbox_volume_ratio": clip01((orbit * face_height * d) / (face_scale**3 + orbit * face_height * d)),
        "orbit_L_bbox_area_ratio": clip01((orbit * face_height) / (face_scale**2 + orbit * face_height)),
        "orbit_R_bbox_area_ratio": clip01((orbit * face_height) / (face_scale**2 + orbit * face_height)),
        "orbit_L_bbox_volume_ratio": clip01((orbit * face_height * d) / (face_scale**3 + orbit * face_height * d)),
        "orbit_R_bbox_volume_ratio": clip01((orbit * face_height * d) / (face_scale**3 + orbit * face_height * d)),
        "orbit_L_ellipse_area_ratio": clip01((orbit * face_width) / (face_scale**2 + orbit * face_width)),
        "orbit_R_ellipse_area_ratio": clip01((orbit * face_width) / (face_scale**2 + orbit * face_width)),
        "orbit_L_ellipse_minor_ratio": clip01(ratio(orbit, face_width + face_height, 0.19)),
        "orbit_R_ellipse_minor_ratio": clip01(ratio(orbit, face_width + face_height, 0.19)),
        "orbit_L_surface_area_ratio": clip01((orbit * face_height + face_width * face_height) / (face_scale**2 + orbit * face_height + face_width * face_height)),
        "orbit_R_surface_area_ratio": clip01((orbit * face_height + face_width * face_height) / (face_scale**2 + orbit * face_height + face_width * face_height)),
        "orbit_L_orbital_bowl_volume_proxy": clip01(0.22 + ratio(orbit + mesh_depth, face_height + face_width, 0.28)),
        "orbit_R_orbital_bowl_volume_proxy": clip01(0.22 + ratio(orbit + mesh_depth, face_height + face_width, 0.28)),
        "orbit_L_convexity_index": clip01(0.21 + ratio(orbit, face_scale, 0.14) + asym * 0.04),
        "orbit_R_convexity_index": clip01(0.21 + ratio(orbit, face_scale, 0.14) + asym * 0.04),
        "zone_orbit_L_plane_residual_p95_ratio": ratio(mesh_depth + orbit, face_height + face_width, 0.2),
        "zone_orbit_R_plane_residual_p95_ratio": ratio(mesh_depth + orbit, face_height + face_width, 0.2),
        "zone_rel_temporal_L_to_orbit_L_normal_angle_deg": 27.0 + ratio(nose_bridge + cheek, face_height + face_width, 11.0) + asym * 6.0,
        "zone_rel_temporal_R_to_orbit_R_normal_angle_deg": 27.0 + ratio(nose_bridge + cheek, face_height + face_width, 11.0) + asym * 6.0,
        "zone_temporal_L_normal_mean_x": clip01(0.38 + side_bias("L") + ratio(nose_bridge, face_scale, 0.1)),
        "zone_temporal_R_normal_mean_x": clip01(0.38 + side_bias("R") + ratio(nose_bridge, face_scale, 0.1)),
        "zone_temporal_L_normal_mean_y": clip01(0.44 + ratio(face_height, face_width + face_height, 0.13)),
        "zone_temporal_R_normal_mean_y": clip01(0.44 + ratio(face_height, face_width + face_height, 0.13)),
        "zone_temporal_L_normal_mean_z": clip01(0.2 + ratio(mesh_depth, face_scale, 0.18)),
        "zone_temporal_R_normal_mean_z": clip01(0.2 + ratio(mesh_depth, face_scale, 0.18)),
        "zone_temporal_L_normal_variance": clip01(asym * 0.12 + ratio(mesh_depth, face_scale, 0.1)),
        "zone_temporal_R_normal_variance": clip01(asym * 0.12 + ratio(mesh_depth, face_scale, 0.1)),
        "zone_temporal_L_span_vertical_ratio": ratio(face_height, w, 0.21),
        "zone_temporal_R_span_vertical_ratio": ratio(face_height, w, 0.21),
        "zone_temporal_L_span_lateral_ratio": ratio(face_width, h, 0.21),
        "zone_temporal_R_span_lateral_ratio": ratio(face_width, h, 0.21),
        "zone_temporal_L_span_depth_ratio": ratio(mesh_depth + face_width, face_height + 1e-6, 0.22),
        "zone_temporal_R_span_depth_ratio": ratio(mesh_depth + face_width, face_height + 1e-6, 0.22),
        "zone_rel_temporal_L_to_orbit_L_distance_ratio": ratio(abs(face_width - orbit) + mesh_depth, face_width + face_height, 0.22),
        "zone_rel_temporal_R_to_orbit_R_distance_ratio": ratio(abs(face_width - orbit) + mesh_depth, face_width + face_height, 0.22),
        "zone_rel_brow_ridge_L_to_jaw_angle_L_distance_ratio": ratio(abs(jaw - nose_bridge) + mesh_depth, face_width + face_height, 0.2),
        "zone_rel_brow_ridge_R_to_jaw_angle_R_distance_ratio": ratio(abs(jaw - nose_bridge) + mesh_depth, face_width + face_height, 0.2),
        "zone_rel_cheekbone_L_to_temporal_L_distance_ratio": ratio(abs(cheek - orbit) + mesh_depth, face_width + face_height, 0.19),
        "zone_rel_cheekbone_R_to_temporal_R_distance_ratio": ratio(abs(cheek - orbit) + mesh_depth, face_width + face_height, 0.2),
        "zone_rel_cheekbone_R_to_temporal_R_normal_angle_deg": 26.0 + ratio(abs(cheek - orbit), face_width + face_height, 12.0) + asym * 4.0,
        "zone_rel_cheekbone_R_to_orbit_R_distance_ratio": ratio(abs(cheek - orbit) + mesh_depth, face_width + face_height, 0.19),
        "zone_rel_jaw_R_to_orbit_R_distance_ratio": ratio(abs(jaw - orbit) + mesh_depth, face_width + face_height, 0.19),
        "zone_ligament_orbital_L_normal_variance": clip01(asym * 0.14 + ratio(mesh_depth + orbit, face_scale, 0.1)),
        "zone_ligament_orbital_R_normal_variance": clip01(asym * 0.14 + ratio(mesh_depth + orbit, face_scale, 0.1)),
        "zone_ligament_orbital_L_normal_mean_y": clip01(0.42 + ratio(orbit, face_width + face_height, 0.11) + side_bias("L") * 0.25),
        "zone_ligament_orbital_R_normal_mean_y": clip01(0.42 + ratio(orbit, face_width + face_height, 0.11) + side_bias("R") * 0.25),
        "zone_ligament_orbital_L_span_depth_ratio": ratio(orbit + mesh_depth, face_height + 1e-6, 0.23),
        "zone_ligament_orbital_R_span_depth_ratio": ratio(orbit + mesh_depth, face_height + 1e-6, 0.23),
        "zone_ligament_orbital_L_span_lateral_ratio": ratio(orbit, face_width + 1e-6, 0.2),
        "zone_ligament_orbital_R_span_lateral_ratio": ratio(orbit, face_width + 1e-6, 0.2),
        "zone_ligament_orbital_L_depth_std_ratio": ratio(mesh_depth + orbit, face_height + face_width, 0.18),
        "zone_ligament_orbital_R_depth_std_ratio": ratio(mesh_depth + orbit, face_height + face_width, 0.18),
        "zone_ligament_orbital_L_normal_mean_x": clip01(0.41 + side_bias("L") + ratio(orbit, face_scale, 0.06)),
        "zone_ligament_orbital_R_normal_mean_x": clip01(0.41 + side_bias("R") + ratio(orbit, face_scale, 0.06)),
        "zone_ligament_orbital_L_normal_mean_z": clip01(0.21 + ratio(mesh_depth + orbit, face_scale, 0.16)),
        "zone_ligament_orbital_R_normal_mean_z": clip01(0.21 + ratio(mesh_depth + orbit, face_scale, 0.16)),
        "zone_ligament_zygomatic_L_normal_variance": clip01(asym * 0.18 + ratio(mesh_depth + cheek, face_scale, 0.09)),
        "zone_ligament_zygomatic_R_normal_variance": clip01(asym * 0.18 + ratio(mesh_depth + cheek, face_scale, 0.09)),
        "zone_ligament_zygomatic_L_normal_mean_y": clip01(0.46 + ratio(cheek, face_height + face_width, 0.16) + side_bias("L") * 0.2),
        "zone_ligament_zygomatic_R_normal_mean_y": clip01(0.46 + ratio(cheek, face_height + face_width, 0.16) + side_bias("R") * 0.2),
        "zone_ligament_zygomatic_L_span_lateral_ratio": ratio(cheek + jaw, face_width + 1e-6, 0.3),
        "zone_ligament_zygomatic_R_span_lateral_ratio": ratio(cheek + jaw, face_width + 1e-6, 0.3),
        "zone_ligament_zygomatic_L_span_depth_ratio": ratio(cheek + mesh_depth, face_height + 1e-6, 0.26),
        "zone_ligament_zygomatic_R_span_depth_ratio": ratio(cheek + mesh_depth, face_height + 1e-6, 0.26),
        "zone_ligament_zygomatic_L_depth_std_ratio": ratio(mesh_depth + cheek, face_height + face_width, 0.22),
        "zone_ligament_zygomatic_R_depth_std_ratio": ratio(mesh_depth + cheek, face_height + face_width, 0.22),
        "zone_rel_temporal_R_to_orbit_R_normal_angle_deg": 24.0 + ratio(nose_bridge + cheek, face_height + face_width, 12.0) + asym * 5.0,
        "R_temporal_to_zygoma_step_ratio": ratio(cheek + mesh_depth, orbit + face_width, 0.32),
        "L_temporal_to_zygoma_step_ratio": ratio(cheek + mesh_depth, orbit + face_width, 0.31),
        "zone_jaw_angle_L_radial_dispersion_ratio": ratio(jaw + mesh_depth, face_width + face_height, 0.24),
        "zone_jaw_angle_R_radial_dispersion_ratio": ratio(jaw + mesh_depth, face_width + face_height, 0.24),
        "zone_jaw_L_radial_dispersion_ratio": ratio(jaw + mesh_depth, face_width + face_height, 0.24),
        "zone_jaw_R_radial_dispersion_ratio": ratio(jaw + mesh_depth, face_width + face_height, 0.24),
        "zone_jaw_R_plane_residual_std_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.31),
        "zone_jaw_R_plane_residual_p95_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.34),
        "zone_jaw_angle_R_plane_residual_std_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.27),
        "zone_jaw_angle_R_plane_residual_p95_ratio": ratio(mesh_depth + jaw, face_height + face_width, 0.3),
        "L_brow_lid_depth_gap_ratio": clip01(1.0 - sym * 0.35 + eye_mouth * 0.1),
        "L_brow_lid_vertical_gap_ratio": ratio(face_height, face_width, 0.08),
        "L_brow_overhang_proxy": clip01(sym * 0.25 + aspect * 0.08),
        "L_eye_socket_bowl_depth": ratio(mesh_depth, face_height, 1.0),
        "L_gonion_to_chin_curve_sharpness": ratio(jaw, face_height, 1.0),
        "L_jaw_depth_span_ratio": ratio(mesh_depth, jaw, 1.0),
        "L_jawline_arc_length_ratio": ratio(jaw, face_width, 1.0),
        "L_lid_surface_curvature": clip01(eye_mouth + sym * 0.12),
        "L_malar_peak_height_ratio": ratio(cheek, face_height, 1.0),
        "L_ramus_height_proxy_ratio": ratio(face_height, jaw, 1.0),
        "L_submalar_hollow_proxy": ratio(cheek, o, 0.5),
        "L_temporal_concavity_proxy": ratio(nose_bridge, face_height, 1.0),
        "L_temporal_to_orbit_depth_gradient": ratio(mesh_depth + nose_bridge, o, 1.0),
        "R_brow_lid_depth_gap_ratio": clip01(1.0 - sym * 0.30 + chin * 0.1),
        "R_brow_lid_vertical_gap_ratio": ratio(face_height, face_width, 0.08),
        "R_brow_overhang_proxy": clip01(sym * 0.22 + aspect * 0.08),
        "R_eye_socket_bowl_depth": ratio(mesh_depth, face_height, 1.0),
        "R_lid_surface_curvature": clip01(eye_mouth + sym * 0.1),
        "R_malar_peak_height_ratio": ratio(cheek, face_height, 1.0),
        "R_submalar_hollow_proxy": ratio(cheek, o, 0.5),
        "R_temporal_concavity_proxy": ratio(nose_bridge, face_height, 1.0),
        "R_temporal_to_orbit_depth_gradient": ratio(mesh_depth + nose_bridge, o, 1.0),
        "L_malar_peak_height_ratio": ratio(cheek, face_height, 1.0),
        "R_malar_peak_height_ratio": ratio(cheek, face_height, 1.0),
        "L_temporal_to_zygoma_step_ratio": ratio(cheek, o + 1e-6, 1.0),
        "R_temporal_to_zygoma_step_ratio": ratio(cheek, o + 1e-6, 1.0),
    }

    return {key: value for key, value in aliases.items() if key in GEOMETRY_CORE_METRICS}
