paths:
  main_input: ${DPTN_DATA_ROOT:-data}/photo/all
  calibration_input: ${DPTN_DATA_ROOT:-data}/photo/calibration
  main_output: ${DPTN_DATA_ROOT:-data}/storage/main
  calibration_output: ${DPTN_DATA_ROOT:-data}/storage/calibration

stages:
  - s1
  - s2
  - s3
  - s4
  - s5
  - s6